### PR TITLE
fix: remove extra padding on CXP client settings box

### PR DESCRIPTION
**Pull request by attfarhan**
This PR changes:

Resolves https://github.com/sourcegraph/sourcegraph/issues/12922

Removes unneeded padding on client settings editor. 

Testing plan:
View the extensions settings page.

Before: 
image
After:
image

I have tested on:

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Phabricator Bundle

### CODE REVIEW

**Comment by chrismwendt** [comment]
You can add "Resolves https://github.com/sourcegraph/sourcegraph/issues/12922" to your PR so that the issue gets closed automatically.

**Comment by felixfbecker** [comment]
Even better, in the commit message footer, see https://conventionalcommits.org/#commit-message-for-a-fix-using-an-optional-issue-number

**Comment by attfarhan** [comment]
@felixfbecker will that auto-close cross-repo issues?

**Comment by felixfbecker** [comment]
Yes

**Comment by felixfbecker** [comment]
Although you might not want to include them in the release notes if they are in a private repo.

**Pull request merged**
